// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKwKVWfwiNybTIvr89JQHLhGkdhLcHNbc',
    appId: '1:326875741493:web:800cd88a4c4eb7b74ca07c',
    messagingSenderId: '326875741493',
    projectId: 'laundry-a478c',
    authDomain: 'laundry-a478c.firebaseapp.com',
    storageBucket: 'laundry-a478c.appspot.com',
    measurementId: 'G-80ZWLXB6S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_IN1FkbAQGMbMPkbbdpAYsmnAGag8bIU',
    appId: '1:326875741493:android:eed49d98edbee9474ca07c',
    messagingSenderId: '326875741493',
    projectId: 'laundry-a478c',
    storageBucket: 'laundry-a478c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOFZWSDN62YVTQtERUfWCk_h-Ym6pMhR0',
    appId: '1:326875741493:ios:1576fdf68938233b4ca07c',
    messagingSenderId: '326875741493',
    projectId: 'laundry-a478c',
    storageBucket: 'laundry-a478c.appspot.com',
    iosBundleId: 'com.example.laundry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOFZWSDN62YVTQtERUfWCk_h-Ym6pMhR0',
    appId: '1:326875741493:ios:89ad26b9ab4355fb4ca07c',
    messagingSenderId: '326875741493',
    projectId: 'laundry-a478c',
    storageBucket: 'laundry-a478c.appspot.com',
    iosBundleId: 'com.example.laundry.RunnerTests',
  );
}
